package com.example.bookstore.service;

import com.example.bookstore.dto.StockHistoryResponse;
import com.example.bookstore.dto.StockResponse;
import com.example.bookstore.entity.Book;
import com.example.bookstore.entity.StockChangeType;
import com.example.bookstore.entity.StockHistory;
import com.example.bookstore.exception.ResourceNotFoundException;
import com.example.bookstore.exception.StockConflictException;
import com.example.bookstore.repository.BookRepository;
import com.example.bookstore.repository.StockHistoryRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;

@Service
public class StockService {

    private final BookRepository bookRepository;
    private final StockHistoryRepository stockHistoryRepository;

    public StockService(BookRepository bookRepository, StockHistoryRepository stockHistoryRepository) {
        this.bookRepository = bookRepository;
        this.stockHistoryRepository = stockHistoryRepository;
    }

    @Transactional(readOnly = true)
    public StockResponse getStock(Long bookId) {
        return toResponse(findOrThrow(bookId));
    }

    @Transactional
    public StockResponse setStock(Long bookId, int stockLevel) {
        Book book = findOrThrow(bookId);
        int previousLevel = book.getStockLevel();
        book.setStockLevel(stockLevel);
        bookRepository.save(book);
        recordHistory(bookId, StockChangeType.SET, previousLevel, stockLevel);
        return new StockResponse(bookId, stockLevel);
    }

    @Transactional
    public StockResponse adjustStock(Long bookId, int delta) {
        Book book = findOrThrow(bookId);

        // Business rule: stock must never drop below zero.
        // SQLite has no CHECK constraint generated by Hibernate for this,
        // so the invariant is enforced here in the service layer.
        int previousLevel = book.getStockLevel();
        int newLevel = previousLevel + delta;
        if (newLevel < 0) {
            // Reject the mutation BEFORE any write reaches the database.
            throw new StockConflictException(
                    "Insufficient stock: cannot reduce stock level below zero.");
        }

        book.setStockLevel(newLevel);
        bookRepository.save(book);
        recordHistory(bookId, StockChangeType.ADJUST, previousLevel, newLevel);
        return new StockResponse(bookId, newLevel);
    }

    @Transactional(readOnly = true)
    public List<StockHistoryResponse> getStockHistory(Long bookId) {
        // 404 for an unknown book id, matching the other stock endpoints.
        findOrThrow(bookId);
        return stockHistoryRepository.findByBookIdOrderByChangedAtAscIdAsc(bookId).stream()
                .map(this::toHistoryResponse)
                .toList();
    }

    private void recordHistory(Long bookId, StockChangeType changeType, int previousLevel, int newLevel) {
        StockHistory history = new StockHistory();
        history.setBookId(bookId);
        history.setChangeType(changeType);
        history.setPreviousLevel(previousLevel);
        history.setNewLevel(newLevel);
        history.setChangedAt(Instant.now().toString());
        stockHistoryRepository.save(history);
    }

    private Book findOrThrow(Long bookId) {
        return bookRepository.findById(bookId)
                .orElseThrow(() -> new ResourceNotFoundException("Book", bookId));
    }

    private StockResponse toResponse(Book book) {
        return new StockResponse(book.getId(), book.getStockLevel());
    }

    private StockHistoryResponse toHistoryResponse(StockHistory history) {
        return new StockHistoryResponse(history.getId(), history.getBookId(), history.getChangeType(),
                history.getPreviousLevel(), history.getNewLevel(), history.getChangedAt());
    }
}
