package com.example.bookstore.service;

import com.example.bookstore.dto.StockResponse;
import com.example.bookstore.entity.Book;
import com.example.bookstore.exception.ResourceNotFoundException;
import com.example.bookstore.exception.StockConflictException;
import com.example.bookstore.repository.BookRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class StockService {

    private final BookRepository bookRepository;

    public StockService(BookRepository bookRepository) {
        this.bookRepository = bookRepository;
    }

    @Transactional(readOnly = true)
    public StockResponse getStock(Long bookId) {
        return toResponse(findOrThrow(bookId));
    }

    @Transactional
    public StockResponse setStock(Long bookId, int stockLevel) {
        Book book = findOrThrow(bookId);
        book.setStockLevel(stockLevel);
        return toResponse(bookRepository.save(book));
    }

    @Transactional
    public StockResponse adjustStock(Long bookId, int delta) {
        Book book = findOrThrow(bookId);

        // Business rule: stock must never drop below zero.
        // SQLite has no CHECK constraint generated by Hibernate for this,
        // so the invariant is enforced here in the service layer.
        int newLevel = book.getStockLevel() + delta;
        if (newLevel < 0) {
            // Reject the mutation BEFORE any write reaches the database.
            throw new StockConflictException(
                    "Insufficient stock: cannot reduce stock level below zero.");
        }

        book.setStockLevel(newLevel);
        return toResponse(bookRepository.save(book));
    }

    private Book findOrThrow(Long bookId) {
        return bookRepository.findById(bookId)
                .orElseThrow(() -> new ResourceNotFoundException("Book", bookId));
    }

    private StockResponse toResponse(Book book) {
        return new StockResponse(book.getId(), book.getStockLevel());
    }
}
